### ISSUE TITLE
wrong check registration == :absent 

### ISSUE THREAD

**Issue by pgassmann** [waveclaw/puppet-subscription_manager#28]
`registration == :absent` should probably be `registration[:ensure] == :absent` or safer `registration.fetch(:ensure, :absent) == :absent`

https://github.com/waveclaw/puppet-subscription_manager/blob/master/lib/puppet/provider/rhsm_register/subscription_manager.rb#L113

**Comment by waveclaw** [comment]
Nice catch.  This was added because the registration was somehow getting set to :absent when it should have been nil under selected combinations of Ruby and Puppet. (See line 147 where that has to be tested in get_registration() along with nil?) 

I have added an extra check for registration[:ensure] == :absent, but have to retain the bug-check.

**Comment by waveclaw** [comment]
And this is why I shouldn't code at 1:30am.  That registration == :absent is actually to catch a weird bug with Ruby 2.0+ and Puppet 4.  I failed the instances test, went back and looked up the cause in my notes and remove it.
