### ISSUE TITLE
problem using a parameters named "environment"

### ISSUE THREAD

**Issue by fduranti** [waveclaw/puppet-subscription_manager#32]
I had many problem with subscription_manager not loading configuration from hiera files.
After various tests I solved all those problems renaming in the manifests and in the function/fact the parameter named "environment" (it's defined in subscription_manager init.pp and used almost everywhere).
After changing that name all seems to work correctly.

**Comment by waveclaw** [comment]
Please provide what version of Puppet you are using, at least if you are using Puppet 3 or 4, and at most the facter, hiera and Puppet versions.

If you are using an unsupported release such as Puppet 4.4 or later with the keyword environment added, that will require version 3.0 of the module to make that breaking change that API exported by the module.

Since there is none of this information at this time I am closing the ticket with an invalid label.
