### ISSUE TITLE
Does not handle version changes in ca_package properly

### ISSUE THREAD

**Issue by robert4man** [waveclaw/puppet-subscription_manager#36]
install.pp:38 should probably be ensure => 'present'  instead of ensure => 'latest'

Mine is failing with:
Error: Could not get latest version: undefined method `backtrace' for Puppet::Error:Class
Error: /Stage[main]/Subscription_manager::Install/Package[katello-ca-consumer-<server name>]/ensure: change from 1.0-3 to latest failed: Could not get latest version: undefined method `backtrace' for Puppet::Error:Class

Changing it to 'present' works around the issue, but it would be nice to be able to handle transitions to new versions as well. At the very least it should be a tunable option and the source should point to the version specific url, i.e. ${::ca_package_prefix}${_pkg}${ca_version} if/when ensure is anything other than 'present'

I'm not sure if 'latest' could ever work properly with the rpm provider type and an http url even though the puppet docs says it is versionable.

I'm using Sat6.2 with puppet 3.8.6-2

**Comment by waveclaw** [comment]
Switching this to `ensure =>'present'` instead of latest _should_ be harmless.  Specifying the direct version is complex enough that I feel you should be maintaining your own code that that point. (That does not preclude accepting a patch with the option, just that I do not plan to do so myself.)

This is because Puppet DSL code tries to install the katello-ca-latest.noarch.rpm from satellite using the bootstrap web service.  This is similar to the bootstrap service for SAM (RedHat Subscription Access Manager) just with a different name than katello.  In both cases the specific package is always a link to the correct versioned CA certificate bundle package.  If not then the service is damaged or misconfigured in a harmful way.

The rpm provider type is correct in declaring versionable. rpm understands `-U` with urls. This is a very loose definition of versioning and has bugs when used with Puppet's idempotent model.  For instance, multiple Linux kernel packages can be installed at the same time but `puppet resource package kernel` only returns the first, usually oldest, in the list.
