### ISSUE TITLE
error removing server.proxy_hostname

### ISSUE THREAD

**Issue by davealden** [waveclaw/puppet-subscription_manager#54]
Hi,
  I've just installed subscription_manager and I am trying to use it for the first time.  I've got the following:

    class { 'subscription_manager':
      server_hostname => $servername,
      org => $org,
      activationkey => $key,
      autosubscribe => true,
      servicelevel => 'STANDARD',
      config_hash => {
        server_prefix => '/rhsm',
        rhsm_baseurl => "https://$servername/pulp/repos",
        rhsm_repo_ca_cert => '%(ca_cert_dir)s/katello-server-ca.pem',
      },
      service_name => 'rhsmcertd',
    }

When I run this, I get:

[...]
****
Debug: Executing: '/usr/sbin/subscription-manager config --remove=server.proxy_hostname'
Error: /Stage[main]/Subscription_manager::Config/Rhsm_config[/etc/rhsm/rhsm.conf]: Could not evaluate: Execution of '/usr/sbin/subscription-manager config --remove=server.proxy_hostname' returned 1: Usage: subscription-manager MODULE-NAME [MODULE-OPTIONS] [--help]
[...]

Of course, if I run "/usr/sbin/subscription-manager config --remove=server.proxy_hostname" by hand, it works just fine.  Help?

**Comment by fduranti** [comment]
Probably related to #53

**Comment by waveclaw** [comment]
Sorry but #53 looks like a formatting error with the YAML input.  In that case nothing is being sent to the provider to remove. Here this is an error with the command actually being run.  

This error is because of how Puppet's provider development works.

For version 3.2.1, in /lib/puppet/provider/rhsm_config/subscription_manager.rb on line 38 to 40 the provider loops through the collected options to remove.

If you call a Puppet command in the provider with a string it will fail.  The command expects that each separate _option_ be provided as an entry in an array.  If you look at how items are applied on line 45, you will see the Ruby `*` operator being used to do this.

This is a valid bug which needs to be resolved and a very specific detail of how to write a provider.

Thank you for bringing this to my attention.

**Comment by waveclaw** [comment]
Just to be clear, what is happening in the 3.2.1 code is that the Ruby interpreter is calling subscription-manager, not your shell.  

Your shell is splitting the parameters into `config` and`--remove=server.proxy_hostname` then sending them to the program.  

Ruby was not.  It was creating a single strange parameter named `config[space]--remove=server.proxy_hostname`.  There is no such strange parameter.

The change in 3.2.2 is to make sure that Ruby splits the parameters as expected by the application.
