### ISSUE TITLE
Puppetrun takes very long if connection to RHN not possible

### ISSUE THREAD

**Issue by mungo312** [waveclaw/puppet-subscription_manager#75]
We are using the module with katello. In our environment a direct connection to rhn is not possible. On the first puppetrun the evaluation of the rhn facts takes very long because subscription-manager tries to list all repos. 

Maybe it would be quite clever to check if the system is registered before checking for the repos ?

**Comment by waveclaw** [comment]
The facts are straight dumb pulls from the `subscription-manager` commands.  These facts do not care if the server is registered, just what the commands return.  In the case of a server connected to RHN this will always be a huge list.

Checking for registration has a few very nasty edge cases.  Since using a Katello server with unknown RHEL licenses and operating in a non-RHN, non-Katello mode are a supported scenario I do not intend to add any probing of registration.
